// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ4VeWJmpUybDWpTiHTwyQOJdcD4XSEnA',
    appId: '1:842291568021:web:81b954f17e63eaf8746a9c',
    messagingSenderId: '842291568021',
    projectId: 'movieapp-f9b6f',
    authDomain: 'movieapp-f9b6f.firebaseapp.com',
    storageBucket: 'movieapp-f9b6f.appspot.com',
    measurementId: 'G-EWPC94HTX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB24fiZE5IVDIbnpc8zOaNrcUmrravUPUQ',
    appId: '1:842291568021:android:5813e1d1d90f8827746a9c',
    messagingSenderId: '842291568021',
    projectId: 'movieapp-f9b6f',
    storageBucket: 'movieapp-f9b6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQARMHRGXHaCm0X89lFF6ihXeAO-QYFbY',
    appId: '1:842291568021:ios:7fb9d9c18b1d9b4e746a9c',
    messagingSenderId: '842291568021',
    projectId: 'movieapp-f9b6f',
    storageBucket: 'movieapp-f9b6f.appspot.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQARMHRGXHaCm0X89lFF6ihXeAO-QYFbY',
    appId: '1:842291568021:ios:7fb9d9c18b1d9b4e746a9c',
    messagingSenderId: '842291568021',
    projectId: 'movieapp-f9b6f',
    storageBucket: 'movieapp-f9b6f.appspot.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ4VeWJmpUybDWpTiHTwyQOJdcD4XSEnA',
    appId: '1:842291568021:web:859c6d3bdeaa54be746a9c',
    messagingSenderId: '842291568021',
    projectId: 'movieapp-f9b6f',
    authDomain: 'movieapp-f9b6f.firebaseapp.com',
    storageBucket: 'movieapp-f9b6f.appspot.com',
    measurementId: 'G-L87BK6P28W',
  );
}
